### ISSUE TITLE
T3-Clustering package or code(images>overview_word_height_profiles.svg)

### ISSUE THREAD

**Issue by YJPark0421** [siebert-julien/time-series-analysis-python#2]
Could you please provide the Python package or your code?
I want draw this graph. Thanks
(ex. deeptime, deltapy, dtaidistance, hypertools, matrixprofile, tslearn)
![image](https://user-images.githubusercontent.com/88306533/211144980-fa0de2bb-9ac2-4249-8c6b-a90def0da70e.png)

**Comment by siebert-julien** [comment]
Dear @YJPark0421 thanks for taking the time to open an issue, but unfortunately I have absolutely no time to pursue and consolidate my overview of time series python packages. I am not going to make my code available as a package. The main reason is that there are fare more advance packages out there.
If you want to do clustering of time series, may I suggest you to have a look at packages such as tslearn https://tslearn.readthedocs.io/en/stable/user_guide/clustering.html (that is basically what I used to make this plot) or sktime https://www.sktime.org/en/stable/api_reference/clustering.html?highlight=clustering 
Best regards, Julien
